### ISSUE TITLE
Saber v1 roadmap

### ISSUE THREAD

**Issue by egoist** [saberland/saber#567]
- [ ] New `saber-browser.js`, `saber-node.js`, and `saber-ssr.js` APIs: no this, try to be close to Gatsby's API
- [ ] New plugin API, just look for saber-*.js in the plugin directory, support local plugins in ./plugins folder
- [ ] Provide a way to query data directly in pages and layouts (possibly in every component?) #560

**Comment by krmax44** [comment]
Maybe for v1, all files with 200+ lines of code could be refactored to be more readable and maintainable.

**Comment by barkdoll** [comment]
Hey egoist, awesome work on Saber. As Vue 3 closes in, I was just wondering, is there eventually going to be planned support for the new Vue 3 features— namely the new composition API?

**Comment by egoist** [comment]
@barkdoll yes, if that would make things easier. I haven't found a use case  for Saber tho 😅

**Comment by barkdoll** [comment]
> @barkdoll yes, if that would make things easier. I haven't found a use case for Saber tho

@egoist awesome. I was just thinking ahead as far as using it to build components, While Saber may not have a specific need for it yet, I think the availability of it will be a huge plus when a use case is discovered.

**Comment by andreasvirkus** [comment]
Throwing it out there... Being built ontop of [vite](https://github.com/vitejs/vite)?

**Comment by egoist** [comment]
@andreasvirkus I'd rather wait for esbuild to be mature, Vite still uses Rollup in production and it's slow too, and it uses different build tools for dev/prod build, that inconsistency might make it harder to debug errors.

**Comment by andreasvirkus** [comment]
Valid point. I used Vitepress for 2 small projects and the DX was lovely and it didn't seem to sacrifise anything else to achieve that DX (but they were quite simple sites and nothing fancy...).

**Comment by egoist** [comment]
I just built something fully using esbuild (and React, since it's hard to use Vue with esbuild for now) https://github.com/egoist/maho

**Comment by egoist** [comment]
@andreasvirkus I was wrong, a Vite based Saber is coming...

**Comment by andreasvirkus** [comment]
That's great! A vite-powered SSG is just what's missing from the Vite ecosystem atm `<3`
